### ISSUE TITLE
inconsistent result of `apply_noise` and `apply_noise!`

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/ImageNoise.jl#7]
```julia
julia> apply_noise!(img, noise) |> summary
"181×181 reinterpret(Float32, ::Array{Gray{Float32},2})"

julia> apply_noise(img, noise) |> summary
"181×181 Array{Gray{Float32},2} with eltype Gray{Float32}"
```

**Comment by RoyiAvital** [comment]
Which denoising algorithms are you going to implement in this package?

**Comment by johnnychen94** [comment]
Good question.

I'm working on a faster WNNM now. I might implemented a faster non-local mean denoiser using the separable property.

I might also re-implement BM3D but that would be a challenge because it's not open sourced.

Unlike repos in JuliaImages, this repo is mostly for my own research interest now so I haven't yet put my efforts to make it widely useable.

Are there any algorithms that you want to see in this repo?

**Comment by RoyiAvital** [comment]
I think Weighted Nuclear Norm, Non Local Means and BM3D is a great start.
What's important and missing in many cases is a good noise properties estimator (Noise Level over the spatial frequency and luminosity value).
It will also be great to have such option for adding noise (Spatially correlated and luminosity dependent).

**Comment by johnnychen94** [comment]
> What's important and missing in many cases is a good noise properties estimator (Noise Level over the spatial frequency and luminosity value).

Yes, I'm totally aware of this! Just that I don't know much about noise estimation. Do you have any recommendations?

> It will also be great to have such option for adding noise (Spatially correlated and luminosity dependent).

I also have this in mind, this repo only contains a very, very basic and trivial `apply_noise` function. If you need more complicated noise adding manners, please feel free to file an issue, or submit a PR.

**Comment by johnnychen94** [comment]
There's also a legacy `imROF` function in Images.jl, which I plan to reimplement a better version here in the future.

**Comment by RoyiAvital** [comment]
I don't have papers on that. From my knowledge on Signal Processing I'd do something like:

1. Use [Variance Stabilizing Transform](https://en.wikipedia.org/wiki/Variance-stabilizing_transformation)  (VST) in order to have noise with its variance constant along the intensity level of the image.
2. Estimate the noise in a multi scale manner. Namely noise level per scale. For each scale one can assume the noise is "White".

Estimating noise given the noise is white and independent of the luminosity level is simpler task. One classic way is using the MAD as done by Donho ([DeNoising by Soft Thresholding](https://ieeexplore.ieee.org/document/382009), Similar idea in [A Median Filter Method for Image Noise Variance Estimation](https://ieeexplore.ieee.org/document/5557339)):

![image](https://user-images.githubusercontent.com/7347975/95819741-5bd14f00-0d2f-11eb-9275-5bcd3b26e2f0.png)

**Comment by johnnychen94** [comment]
Thanks for the direction! I'll definitely take a look at them.
